serenity.project.name=B2B Quoting Engine - FluentWait PoC
serenity.test.root=src/test/java
serenity.outputDirectory=build/reports/serenity
serenity.take.screenshots=FOR_EACH_ACTION
serenity.screenshot.format=PNG
webdriver.autodownload=true
